name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm install pkg
        
    - name: PKG
      run: |
        echo "pkg main.js -C Brotli -t  latest-macos-x64"
        tar -czvf main.tar.gz ./main
        ls

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: main
        path: ./main
        
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        repository: guido.selinger/it-objects
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Move artifact
      run: mv main aws-rds-helper
