name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install -g pkg
        npm install wait-console-input
        npm install inquirer
        pkg awsrdshelper.js -C Brotli -t  latest-macos-x64
        ls
        chmod a+x awsrdshelper
        tar -czvf awsrdshelper.tar.gz ./awsrdshelper
        ls

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: awsrdshelper
        path: ./awsrdshelper
        
    - name: Commit artifact
      run: |
        git config --global user.name guido.selinger
        git config --global user.email guido.selinger@it-objects.de
        git add .
        git commit -m "Add artifact"

    - name: Push changes
      run: git push

    - name: Create Tag
      run: |
        current_tag=$(git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0")
        IFS='.' read -r -a version_parts <<< "${current_tag:1}"
        major="${version_parts[0]}"
        minor="${version_parts[1]}"
        patch="${version_parts[2]}"
        new_tag="v$major.$minor.$((patch + 1))"

        git tag "$new_tag"
        git push origin "$new_tag"
