name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm install pkg
        
    - name: PKG
      run: |
        echo "pkg main.js -C Brotli -t  latest-macos-x64"
        echo "mv ./main ./aws-helper"
        chmod a+x aws-helper
        tar -czvf aws-helper.tar.gz ./aws-helper
        ls

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: aws-helper
        path: ./aws-helper
        
    - name: Commit artifact
      run: |
        git config --global user.name guido.selinger
        git config --global user.email guido.selinger@it-objects.de
        git add .
        git commit -m "Add artifact"

    - name: Push changes
      run: git push

    - name: Create Tag
      run: |
        git tag -a v1.0.1 -m "Version 1.0.1"
        git push origin v1.0.1
