name: Increment Tag Version

on:
  push:
    tags:
      - '*'

jobs:
  increment_tag_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.email guido.selinger@it-objects.de
          git config --local user.name guido.selinger

      - name: Get the latest tag
        id: get_latest_tag
        run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags)

      - name: Increment tag version
        id: increment_tag
        run: |
          # Extract the current tag version
          CURRENT_TAG=${{ steps.get_latest_tag.outputs.tag }}
          echo "Current tag: $CURRENT_TAG"

          # Increment the tag version
          IFS='.' read -r -a VERSION <<< "$CURRENT_TAG"
          MAJOR=${VERSION[0]}
          MINOR=${VERSION[1]}
          PATCH=${VERSION[2]}
          NEW_TAG="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "New tag: $NEW_TAG"

          # Create a new tag
          git tag $NEW_TAG
          git push origin $NEW_TAG
