name: Increment Version Tag

on:
  push:
    branches:
      - main

jobs:
  increment_version_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current version tag
        id: get_version
        run: |
          # Get the latest version tag
          VERSION=$(git describe --abbrev=0 --tags)
          echo "::set-output name=version::$VERSION"

      - name: Increment version
        id: increment_version
        run: |
          # Increment the version number
          VERSION=$(echo "${{ steps.get_version.outputs.version }}" | awk -F. -v OFS=. '{$NF++;print}')
          echo "::set-output name=version::$VERSION"

      - name: Create new version tag
        id: create_tag
        run: |
          # Create a new version tag
          git tag ${{ steps.increment_version.outputs.version }}
          echo "::set-output name=tag::$VERSION"

      - name: Push new tag
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.create_tag.outputs.tag }}
